#!/bin/bash
# Template for a standard shell env

#SBATCH --job-name=running_single_process
#SBATCH --time=02:00:00
#SBATCH --ntasks=8
#SBATCH --nodes=1
#SBATCH --mem-per-cpu=6G
#SBATCH --output=out.1
#SBATCH --error=error.1

  

module purge
module load intel/2022a
mpiicpc -o qsort_hypercube.exe qsort_hypercube.cpp
echo "one process, 20480000 size"
mpirun -np 1 ./qsort_hypercube.exe 20480000 0
echo "1 p, 40960000 size"
mpirun -np 1 ./qsort_hypercube.exe 40960000 0
echo "1 p, 81920000 size"
mpirun -np 1 ./qsort_hypercube.exe 81920000 0
echo "1 p, 163840000 size"
mpirun -np 1 ./qsort_hypercube.exe 163840000 0
echo "1 p, 327680000 size"
mpirun -np 1 ./qsort_hypercube.exe 327680000 0
echo "1 p, 655360000 size"
mpirun -np 1 ./qsort_hypercube.exe 655360000 0
echo "1 p, 1310720000 size"
mpirun -np 1 ./qsort_hypercube.exe 1310720000 0
